### ISSUE TITLE
heres a new logo for the mod. ur wlcm :)

### ISSUE THREAD

**Issue by xNotFlow** [DrexHD/OrderedPlayerList#11]
![119951bd-831d-4df4-859c-38610d1ed086](https://github.com/user-attachments/assets/f361ad7a-bbae-4b6a-9ab6-ea68afa06fb7)

**Comment by xNotFlow** [comment]
thought id help in replacing the mod logo so i ai generated this

**Comment by DrexHD** [comment]
Sorry, I am not interested in ai generated logos

**Comment by xNotFlow** [comment]
alr
