### ISSUE TITLE
Quick question [Styled Player List vs Ordered Player List]

### ISSUE THREAD

**Issue by Skullians** [DrexHD/OrderedPlayerList#9]
Hey, I'm assuming ordered player list **replaces** Styled Player List?
Or can you have them together?
Just want to avoid having to configure everything again.

**Comment by arnokeesman** [comment]
OPL is just another mod, almost exclusively taking care of ordering
It's meant to be used alongside SPL, though it can probably work without it

**Comment by Skullians** [comment]
Right. Thanks for your time
